version: "3.8"

services:
  app:
    container_name: php7.4-apache-container-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
  #   depends_on:
  #     - db
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #   volumes:
  #     - ./db_data:/var/lib/mysql
